name: Terraform Deploy VM
on: [push]

jobs:
  terraform-deploy:
    runs-on: [ubuntu-22.04]  # Метка вашего раннера
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Local Provider Cache
        run: |
          # КЛЮЧЕВОЙ ШАГ: Указываем Terraform использовать локальные плагины
          cat > /tmp/terraform.rc << 'EOF'
          provider_installation {
            filesystem_mirror {
              path    = "/root/.terraform.d/plugins"
              include = ["registry.terraform.io/*/*"]
            }
          }
          EOF
          export TF_CLI_CONFIG_FILE=/tmp/terraform.rc

      - name: Terraform Init & Plan
        run: |
          cd master/
          terraform init
          terraform plan
        env:
          PM_API_URL: ${{ secrets.PM_API_URL }}
          PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
          PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}

      - name: Terraform Apply
        run: |
          cd master/
          terraform apply -auto-approve
        env:
          PM_API_URL: ${{ secrets.PM_API_URL }}
          PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
          PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
