name: Terraform Deploy VM
on: [push]

jobs:
  terraform-deploy:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean Terraform Cache
        run: |
          cd master/
          rm -rf .terraform .terraform.lock.hcl

      - name: Terraform Init & Plan
        run: |
          cd master/
          terraform init
          terraform plan -input=false -out=tfplan
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}

      - name: Terraform Apply
        run: |
          cd master/
          terraform apply -input=false -auto-approve tfplan
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
