name: Terraform Deploy VM
on: [push]

jobs:
  terraform-deploy:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Копируем ЕДИНЫЙ файл конфигурации туда, где его увидит Terraform
      - name: Prepare Configuration
        working-directory: .  # ВСЕ команды ниже выполняются из корня репозитория
        run: |
          echo "=== Текущая директория (должна быть корень репозитория) ==="
          pwd
          echo "=== Содержимое корня ==="
          ls -la
          echo "=== Копируем config.auto.tfvars в master/ ==="
          cp config.auto.tfvars master/
          echo "=== Проверяем копирование ==="
          ls -la master/config.auto.tfvars
          echo "--- Проверяем ключевое значение target_node в файле ---"
          grep target_node master/config.auto.tfvars

      - name: Generate SSH Key
        run: |
          apk add --no-cache openssh-client
          mkdir -p /root/.ssh
          if [ ! -f /root/.ssh/id_ed25519 ]; then
            ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N "" -q
            echo "SSH Public Key generated:"
            cat /root/.ssh/id_ed25519.pub
          else
            echo "SSH Key already exists:"
            cat /root/.ssh/id_ed25519.pub
          fi

      - name: Configure Terraform Local Cache
        run: |
          cat > /root/.terraformrc << 'EOF'
          provider_installation {
            filesystem_mirror {
              path    = "/root/.terraform.d/plugins"
              include = ["registry.terraform.io/*/*"]
            }
            direct {
              exclude = ["registry.terraform.io/*/*"]
            }
          }
          EOF

      - name: Clean Terraform Cache
        run: |
          cd master/
          rm -rf .terraform .terraform.lock.hcl

      # Terraform УВИДИТ config.auto.tfvars в папке master/ и использует ВСЕ настройки из него
      - name: Terraform Init & Plan
        run: |
          cd master/
          terraform init
          terraform plan -input=false -out=tfplan
        env:
          # ТОЛЬКО СЕКРЕТЫ. Все остальные настройки - из config.auto.tfvars
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}

      - name: Terraform Apply
        run: |
          cd master/
          terraform apply -input=false -auto-approve tfplan
        env:
          # ТОЛЬКО СЕКРЕТЫ. Все остальные настройки - из config.auto.tfvars
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
