name: Deploy K8s Cluster
on: [push]

jobs:
  deploy:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SSH Key
        run: |
          mkdir -p /root/.ssh
          ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N "" -q
          echo "=== SSH Public Key ==="
          cat /root/.ssh/id_ed25519.pub

      - name: Check IP Range Availability
        run: |
          echo "=== Проверка диапазона IP адресов ==="
          
          if [ ! -f config.auto.tfvars ]; then
            echo "❌ Файл config.auto.tfvars не найден!"
            exit 1
          fi
          
          # Чтение переменных БЕЗ сложных кавычек
          SUBNET=$(grep 'subnet' config.auto.tfvars | cut -d'"' -f2)
          STATIC_BASE=$(grep 'static_ip_base' config.auto.tfvars | awk '{print $3}')
          MASTERS_COUNT=$(grep 'masters_count' config.auto.tfvars | awk '{print $3}')
          WORKERS_COUNT=$(grep 'workers_count' config.auto.tfvars | awk '{print $3}')
          
          echo "Сеть: $SUBNET"
          echo "Базовый IP: $STATIC_BASE"
          echo "Мастер-нод: $MASTERS_COUNT"
          echo "Воркер-нод: $WORKERS_COUNT"
          
          if [ -z "$SUBNET" ] || [ -z "$STATIC_BASE" ] || [ -z "$MASTERS_COUNT" ] || [ -z "$WORKERS_COUNT" ]; then
            echo "❌ Не удалось прочитать настройки из config.auto.tfvars"
            echo "Проверьте формат файла!"
            exit 1
          fi
          
          NETWORK_PREFIX=$(echo "$SUBNET" | cut -d'/' -f1 | cut -d. -f1-3)
          TOTAL_NODES=$((MASTERS_COUNT + WORKERS_COUNT))
          
          echo "=== Проверка $TOTAL_NODES IP адресов ($NETWORK_PREFIX.$STATIC_BASE-$((STATIC_BASE + TOTAL_NODES - 1))) ==="
          
          ALL_FREE=true
          for i in $(seq 0 $((TOTAL_NODES - 1))); do
            IP_INDEX=$((STATIC_BASE + i))
            CHECK_IP="${NETWORK_PREFIX}.${IP_INDEX}"
            
            echo -n "  $CHECK_IP ... "
            if ping -c 1 -W 1 "$CHECK_IP" >/dev/null 2>&1; then
              echo "ЗАНЯТ ❌"
              ALL_FREE=false
            else
              echo "свободен ✅"
            fi
          done
          
          if [ "$ALL_FREE" = false ]; then
            echo "❌ Некоторые IP адреса уже заняты!"
            echo "Измените static_ip_base в config.auto.tfvars"
            exit 1
          else
            echo "✅ Все IP адреса свободны"
          fi

      - name: Clean Terraform Cache
        run: |
          echo "=== Очистка Terraform кэша ==="
          rm -rf .terraform .terraform.lock.hcl 2>/dev/null || true
          echo "Кэш очищен"

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
